<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:include filename="inertial_macros.xacro"/>

    <xacro:property name="chassis_length" value="0.444"/>
    <xacro:property name="chassis_width" value="0.444"/>
    <xacro:property name="chassis_height" value="0.152"/>
    <xacro:property name="chassis_mass" value="1.0"/>
    <xacro:property name="wheel_radius" value="0.076"/>
    <xacro:property name="wheel_thickness" value="0.076"/>
    <xacro:property name="wheel_mass" value="0.05"/>
    <xacro:property name="wheel_offset_x" value="0.226"/>
    <xacro:property name="wheel_offset_y" value="0.1485"/>
    <xacro:property name="wheel_offset_z" value="0.01"/>
        
    <xacro:property name="caster_wheel_radius" value="0.08"/>
    <xacro:property name="caster_wheel_mass" value="0.01"/>
    <xacro:property name="caster_wheel_offset_x" value="0.075"/>
    <xacro:property name="caster_wheel_offset_z" value="${wheel_offset_z - wheel_radius + caster_wheel_radius}"/>
<!-- need to be check the above -->


    <!-- robot apearence -->
    <material name="white"> 
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

 <!-- BASE LINK -->
    <link name="base_link">
    </link>
<!-- BASE_FOOTPRINT LINK -->
    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">
    </link>
 <!-- CHASSIS LINK -->
    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="-0.1 0 0"/> <!--<origin xyz="${-wheel_offset_x} 0 ${-wheel_offset_z}"/>--><!-- here the origin is set just behind the mid of chessi-->
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="0.22 0 0.075"/>
            <geometry>
                <box size="0.44 0.44 0.15"/><!-- <box size="${chassis_length} ${chassis_width} ${chassis_height}"/> -->
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="0.22 0 0.075"/>
            <geometry>
                <box size="0.44 0.44 0.15"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="0.44" y="0.44" z="0.15"><!-- <xacro:inertial_box mass="0.5" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}"> -->
             <origin xyz="0.22 0 0.075" rpy="0 0 0"/><!--<origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/> -->
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/Orange</material>
    </gazebo>

    <!-- LEFT WHEEL LINK -->
    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 0.175 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/> 
    </joint>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="0.08" length="0.08"/><!-- <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>/-->
            </geometry>

            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="0.08"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.1" length="0.08" radius="0.08"><!-- <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}"> -->
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

    <!-- RIGHT WHEEL LINK -->

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 -0.175 0" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="0.08" length="0.08"/> <!-- <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>/-->
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="0.08"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.1" length="0.08" radius="0.08"><!-- <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}"> -->
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="right_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>
    
    <!-- CASTER WHEEL 1 LINK -->

    <joint name="caster_wheel_joint_1" type="fixed">
        <parent link="chassis"/>
        <child link="caster_wheel_1"/>
        <origin xyz="0.22225 0 0.1016"/><!-- <origin xyz="${caster_wheel_offset_x} 0 ${caster_wheel_offset_z}"/> -->
    </joint>

    <link name="caster_wheel_1">
        <visual>
            <geometry>
                <sphere radius="0.08"/><!-- <sphere radius="${caster_wheel_radius}"/> -->
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="0.08"/>
            </geometry>
        </collision>
            <xacro:inertial_sphere mass="0.01" radius="0.08"><!-- <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}"> -->
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="caster_wheel_1">
        <material>Gazebo/White</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>
    
    <!-- CASTER WHEEL 2 LINK -->

    <joint name="caster_wheel_joint_2" type="fixed">
        <parent link="chassis"/>
        <child link="caster_wheel_2"/>
        <origin xyz="-0.22175 0 0.1016"/><!-- <origin xyz="${caster_wheel_offset_x} 0 ${caster_wheel_offset_z}"/> -->
    </joint>

    <link name="caster_wheel_2">
        <visual>
            <geometry>
                <sphere radius="0.08"/><!-- <sphere radius="${caster_wheel_radius}"/> -->
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="0.08"/>
            </geometry>
        </collision>
            <xacro:inertial_sphere mass="0.01" radius="0.08"><!-- <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}"> -->
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="caster_wheel_2">
        <material>Gazebo/White</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

</robot>
